"""
Django settings for pltx_dashboard project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-@9e3vk548@g^lc3ke$4_s^sh%(pj=3utzz7=5^*ea34p8g!0gh"

def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_int(name, default):
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", True)

ALLOWED_HOSTS = ['209.182.233.109','admin.plantex.work','desk.sapiosol.com','127.0.0.1']

CSRF_TRUSTED_ORIGINS = [
    'https://admin.plantex.work',
    'http://admin.plantex.work',
    'https://desk.sapiosol.com',
    'http://desk.sapiosol.com',
    'https://209.182.233.109',
    'http://209.182.233.109',
    'http://127.0.0.1',
    'http://localhost:8000',
]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "channels",
    "apps.accounts",
    "apps.upload",
    "apps.dashboard",
    "apps.replenishment",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "apps.dashboard.middleware.DashboardQueryProfilingMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pltx_dashboard.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.dashboard.context_processors.stock_upload_alert",
            ],
        },
    },
]

WSGI_APPLICATION = "pltx_dashboard.wsgi.application"
ASGI_APPLICATION = "pltx_dashboard.asgi.application"

# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('redis', 6379)],   # 🔥 FIX
#         },
#     },
# }

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
            # Reduce stale websocket queue buildup and absorb short message bursts.
            "capacity": 800,
            "expiry": 15,
            "group_expiry": 300,
        },
    },
}

# Celery Configuration Options
# CELERY_BROKER_URL = 'redis://redis:6379/0'      # 🔥 FIX
# CELERY_RESULT_BACKEND = 'redis://redis:6379/0'  # 🔥 FIX
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/2'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/2'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'
# Report STARTED state so frontend can distinguish "queued" from "actively running"
CELERY_TASK_TRACK_STARTED = True
# Expire task results after 1 hour to avoid Redis bloat
CELERY_TASK_RESULT_EXPIRES = 3600
CELERY_BEAT_SCHEDULE = {
    "dashboard-materialized-summary-cleanup-nightly": {
        "task": "apps.dashboard.tasks.cleanup_dashboard_materialized_summaries_task",
        "schedule": crontab(minute=25, hour=3),
    },
    "dashboard-daily-summary-refresh-nightly": {
        "task": "apps.dashboard.tasks.refresh_all_dashboard_daily_summaries_task",
        "schedule": crontab(minute=45, hour=3),
    },
    "dashboard-product-daily-summary-refresh-nightly": {
        "task": "apps.dashboard.tasks.refresh_all_dashboard_product_daily_summaries_task",
        "schedule": crontab(minute=55, hour=3),
    },
    "dashboard-inventory-summary-refresh-nightly": {
        "task": "apps.dashboard.tasks.refresh_all_dashboard_inventory_summaries_task",
        "schedule": crontab(minute=10, hour=4),
    },
}

# ─── Shared Redis Cache ───────────────────────────────────────────────────────
# IMPORTANT: Must use Redis (not the default LocMemCache) so that cache writes
# from the Celery worker process (e.g. bumping dashboard_data_version after an
# upload) are visible to the Daphne web process. LocMemCache is per-process and
# would silently discard all cross-process cache invalidation.
# Redis DB 1 is used here to keep it separate from the Celery broker (DB 0).
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "db": "1",
        },
        "TIMEOUT": 86400,  # 24 hours default
    }
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'plantex_db',
#         'USER': 'plantex',
#         'PASSWORD': 'strongAppPass123',
#         'HOST': 'mysql',   # 🔥 THIS IS THE FIX
#         'PORT': '3306',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "pltx_dashboard",
        "USER": "root",
        "PASSWORD": "",
        "HOST": "127.0.0.1",
        "PORT": "3306",
        "CONN_MAX_AGE": 300,
        "OPTIONS": {
            "local_infile": 1,
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # ✅ ADD THIS

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

CORS_ALLOW_ALL_ORIGINS = True

# Authentication redirects
LOGIN_URL = "/accounts/login/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# File upload limits — keep request body generous, but force temp-file handling
# for large uploads to avoid expensive in-memory buffering/copies.
DATA_UPLOAD_MAX_MEMORY_SIZE = max(env_int("DATA_UPLOAD_MAX_MEMORY_SIZE", 629145600), 10485760)
FILE_UPLOAD_MAX_MEMORY_SIZE = max(env_int("FILE_UPLOAD_MAX_MEMORY_SIZE", 8388608), 1048576)
DATA_UPLOAD_MAX_NUMBER_FILES = 20

# Frontend polling timeout for upload Celery tasks (seconds).
# Large historical refreshes can legitimately take longer than a few minutes.
UPLOAD_TASK_TIMEOUT_SECONDS = max(env_int("UPLOAD_TASK_TIMEOUT_SECONDS", 1800), 60)
# Keep source files in uploads/ after processing (set False to auto-delete).
UPLOAD_KEEP_FILES = env_bool("UPLOAD_KEEP_FILES", True)

# Dashboard materialized summary retention + warmup.
DASHBOARD_SUMMARY_RETENTION_DAYS = max(
    env_int("DASHBOARD_SUMMARY_RETENTION_DAYS", 14), 1
)
DASHBOARD_SUMMARY_MAX_ROWS_PER_VIEW = max(
    env_int("DASHBOARD_SUMMARY_MAX_ROWS_PER_VIEW", 800), 50
)
DASHBOARD_WARMUP_ENABLED = env_bool("DASHBOARD_WARMUP_ENABLED", True)
DASHBOARD_WARMUP_MAX_FILTER_SETS = max(
    env_int("DASHBOARD_WARMUP_MAX_FILTER_SETS", 7), 1
)
DASHBOARD_DAILY_SUMMARY_ENABLED = env_bool("DASHBOARD_DAILY_SUMMARY_ENABLED", True)
DASHBOARD_PRODUCT_DAILY_SUMMARY_ENABLED = env_bool(
    "DASHBOARD_PRODUCT_DAILY_SUMMARY_ENABLED", True
)
DASHBOARD_INVENTORY_SUMMARY_ENABLED = env_bool("DASHBOARD_INVENTORY_SUMMARY_ENABLED", True)
DASHBOARD_MODAL_ROWS_CACHE_TTL_SECONDS = max(
    env_int("DASHBOARD_MODAL_ROWS_CACHE_TTL_SECONDS", 604800), 60
)

# Slow-query / endpoint profiling for dashboard pages.
DASHBOARD_QUERY_PROFILING_ENABLED = env_bool("DASHBOARD_QUERY_PROFILING_ENABLED", True)
DASHBOARD_SLOW_QUERY_MS = max(env_int("DASHBOARD_SLOW_QUERY_MS", 200), 50)
DASHBOARD_SLOW_ENDPOINT_MS = max(env_int("DASHBOARD_SLOW_ENDPOINT_MS", 800), 100)
DASHBOARD_TOP_EXPENSIVE_QUERIES = max(env_int("DASHBOARD_TOP_EXPENSIVE_QUERIES", 5), 1)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'loggers': {
        'daphne.server': {
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
