# Generated by Django 6.0.3 on 2026-04-14 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_feature_users_created_by_users_is_main_user_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="is_main_user",
        ),
    ]
