# Generated by Django 6.0.3 on 2026-04-07 07:24

import apps.upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(storage=apps.upload.models.OverwriteStorage(), upload_to=apps.upload.models.user_directory_path),
        ),
    ]
