# Generated by Django 6.0.3 on 2026-04-14 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0002_alter_uploadedfile_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
