# Generated by Django 6.0.3 on 2026-05-07 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('upload', '0003_delete_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('success', 'Success'), ('error', 'Error')], db_index=True, default='queued', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_logs', to='accounts.users')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_file_logs', to='accounts.users')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['data_owner', 'created_at'], name='idx_uplog_owner_dt'), models.Index(fields=['data_owner', 'status'], name='idx_uplog_owner_st')],
            },
        ),
    ]
