# Generated by Django 6.0.3 on 2026-06-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadlog',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='queued', max_length=20),
        ),
    ]
