from django.db import models

class SalesData(models.Model):
    user = models.ForeignKey('accounts.Users', on_delete=models.CASCADE, related_name='sales_records')
    date = models.DateField(db_index=True)
    asin = models.CharField(max_length=50, db_index=True)
    pageviews = models.IntegerField(default=0)
    units = models.IntegerField(default=0)
    orders = models.IntegerField(default=0)
    revenue = models.FloatField(default=0.0)

    class Meta:
        unique_together = ('user', 'date', 'asin')

class SpendData(models.Model):
    user = models.ForeignKey('accounts.Users', on_delete=models.CASCADE, related_name='spend_records')
    date = models.DateField(db_index=True)
    asin = models.CharField(max_length=50, db_index=True)
    ad_account = models.CharField(max_length=100)
    ad_type = models.CharField(max_length=10)
    spend = models.FloatField(default=0.0)

    class Meta:
        unique_together = ('user', 'date', 'asin', 'ad_account', 'ad_type')

class CategoryMapping(models.Model):
    user = models.ForeignKey('accounts.Users', on_delete=models.CASCADE, related_name='category_mappings')
    asin = models.CharField(max_length=50, db_index=True)
    portfolio = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    subcategory = models.CharField(max_length=100)

    class Meta:
        unique_together = ('user', 'asin')

class PriceData(models.Model):
    user = models.ForeignKey('accounts.Users', on_delete=models.CASCADE, related_name='price_data')
    asin = models.CharField(max_length=50, db_index=True)
    price = models.FloatField(default=0.0)

    class Meta:
        unique_together = ('user', 'asin')

class ProcessedDashboardData(models.Model):
    user = models.ForeignKey('accounts.Users', on_delete=models.CASCADE, related_name='processed_dashboard_data')
    date = models.DateField(db_index=True)
    asin = models.CharField(max_length=50, db_index=True)
    portfolio = models.CharField(max_length=100, db_index=True, null=True, blank=True)
    category = models.CharField(max_length=100, db_index=True, null=True, blank=True)
    subcategory = models.CharField(max_length=100, db_index=True, null=True, blank=True)
    price = models.FloatField(default=0.0)
    
    pageviews = models.IntegerField(default=0)
    units = models.IntegerField(default=0)
    orders = models.IntegerField(default=0)
    revenue = models.FloatField(default=0.0)
    
    spend_sp = models.FloatField(default=0.0)
    spend_sb = models.FloatField(default=0.0)
    spend_sd = models.FloatField(default=0.0)
    total_spend = models.FloatField(default=0.0)

    class Meta:
        unique_together = ('user', 'date', 'asin')
        indexes = [
            models.Index(fields=['user', 'category', 'date'], name='idx_user_cat_date'),
        ]

class FlipkartSalesReport(models.Model):
    user = models.ForeignKey('accounts.Users', on_delete=models.CASCADE, related_name='flipkart_sales_reports')
    seller_gstin = models.CharField(max_length=100, null=True, blank=True)
    order_id = models.CharField(max_length=100, db_index=True)
    order_item_id = models.CharField(max_length=100, db_index=True)
    product_title_description = models.CharField(max_length=500, null=True, blank=True)
    fsn = models.CharField(max_length=100, db_index=True, null=True, blank=True)
    sku = models.CharField(max_length=100, db_index=True, null=True, blank=True)
    hsn_code = models.CharField(max_length=100, null=True, blank=True)
    event_type = models.CharField(max_length=100, null=True, blank=True)
    event_sub_type = models.CharField(max_length=100, null=True, blank=True)
    order_type = models.CharField(max_length=100, null=True, blank=True)
    fulfilment_type = models.CharField(max_length=100, null=True, blank=True)
    order_date = models.DateTimeField(null=True, blank=True)
    order_approval_date = models.DateTimeField(null=True, blank=True)
    item_quantity = models.IntegerField(default=0)
    order_shipped_from_state = models.CharField(max_length=100, null=True, blank=True)
    warehouse_id = models.CharField(max_length=100, null=True, blank=True)
    price_before_discount = models.FloatField(default=0.0)
    total_discount = models.FloatField(default=0.0)
    seller_share = models.FloatField(default=0.0)
    bank_offer_share = models.FloatField(default=0.0)
    price_after_discount = models.FloatField(default=0.0)
    shipping_charges = models.FloatField(default=0.0)
    final_invoice_amount = models.FloatField(default=0.0)
    type_of_tax = models.CharField(max_length=100, null=True, blank=True)
    taxable_value = models.FloatField(default=0.0)
    cst_rate = models.FloatField(default=0.0)
    cst_amount = models.FloatField(default=0.0)
    vat_rate = models.FloatField(default=0.0)
    vat_amount = models.FloatField(default=0.0)
    luxury_cess_rate = models.FloatField(default=0.0)
    luxury_cess_amount = models.FloatField(default=0.0)
    igst_rate = models.FloatField(default=0.0)
    igst_amount = models.FloatField(default=0.0)
    cgst_rate = models.FloatField(default=0.0)
    cgst_amount = models.FloatField(default=0.0)
    sgst_rate = models.FloatField(default=0.0)
    sgst_amount = models.FloatField(default=0.0)
    tcs_igst_rate = models.FloatField(default=0.0)
    tcs_igst_amount = models.FloatField(default=0.0)
    tcs_cgst_rate = models.FloatField(default=0.0)
    tcs_cgst_amount = models.FloatField(default=0.0)
    tcs_sgst_rate = models.FloatField(default=0.0)
    tcs_sgst_amount = models.FloatField(default=0.0)
    total_tcs_deducted = models.FloatField(default=0.0)
    buyer_invoice_id = models.CharField(max_length=100, null=True, blank=True)
    buyer_invoice_date = models.DateTimeField(null=True, blank=True)
    buyer_invoice_amount = models.FloatField(default=0.0)
    customer_billing_pincode = models.CharField(max_length=50, null=True, blank=True)
    customer_billing_state = models.CharField(max_length=100, null=True, blank=True)
    customer_delivery_pincode = models.CharField(max_length=50, null=True, blank=True)
    customer_delivery_state = models.CharField(max_length=100, null=True, blank=True)
    usual_price = models.FloatField(default=0.0)
    is_shopsy_order = models.CharField(max_length=50, null=True, blank=True)
    tds_rate = models.FloatField(default=0.0)
    tds_amount = models.FloatField(default=0.0)
    irn = models.CharField(max_length=100, null=True, blank=True)
    business_name = models.CharField(max_length=255, null=True, blank=True)
    business_gst_number = models.CharField(max_length=100, null=True, blank=True)
    beneficiary_name = models.CharField(max_length=255, null=True, blank=True)
    imei = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        unique_together = ('user', 'order_id', 'order_item_id')

class FlipkartCurrentInventoryReport(models.Model):
    user = models.ForeignKey('accounts.Users', on_delete=models.CASCADE, related_name='flipkart_inventory_reports')
    warehouse_id = models.CharField(max_length=100, null=True, blank=True)
    sku = models.CharField(max_length=100, db_index=True)
    title = models.CharField(max_length=255, null=True, blank=True)
    listing_id = models.CharField(max_length=100, null=True, blank=True)
    fsn = models.CharField(max_length=100, db_index=True, null=True, blank=True)
    brand = models.CharField(max_length=100, null=True, blank=True)
    flipkart_selling_price = models.FloatField(default=0.0)
    live_on_website = models.CharField(max_length=50, null=True, blank=True)
    sales_7d = models.IntegerField(default=0)
    sales_14d = models.IntegerField(default=0)
    sales_30d = models.IntegerField(default=0)
    sales_60d = models.IntegerField(default=0)
    sales_90d = models.IntegerField(default=0)
    b2b_scheduled = models.IntegerField(default=0)
    transfers_scheduled = models.IntegerField(default=0)
    b2b_shipped = models.IntegerField(default=0)
    transfers_shipped = models.IntegerField(default=0)
    b2b_receiving = models.IntegerField(default=0)
    transfers_receiving = models.IntegerField(default=0)
    reserved_for_orders_and_recalls = models.IntegerField(default=0)
    reserved_for_internal_processing = models.IntegerField(default=0)
    returns_processing = models.IntegerField(default=0)
    orders_to_dispatch = models.IntegerField(default=0)
    recalls_to_dispatch = models.IntegerField(default=0)
    damaged = models.IntegerField(default=0)
    qc_reject = models.IntegerField(default=0)
    catalog_reject = models.IntegerField(default=0)
    returns_reject = models.IntegerField(default=0)
    seller_return_reject = models.IntegerField(default=0)
    miscellaneous = models.IntegerField(default=0)
    length_in_cm = models.FloatField(default=0.0)
    breadth_in_cm = models.FloatField(default=0.0)
    height_in_cm = models.FloatField(default=0.0)
    weight_in_kg = models.FloatField(default=0.0)
    fulfilment_type = models.CharField(max_length=100, null=True, blank=True)
    f_assured_badge = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        unique_together = ('user', 'warehouse_id', 'sku')

class PCADailyReport(models.Model):
    user = models.ForeignKey('accounts.Users', on_delete=models.CASCADE, related_name='pca_daily_reports')
    start_time = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    campaign_id = models.CharField(max_length=100, null=True, blank=True)
    campaign_name = models.CharField(max_length=255, null=True, blank=True)
    ad_group_id = models.CharField(max_length=100, null=True, blank=True)
    ad_group_name = models.CharField(max_length=255, null=True, blank=True)
    date = models.DateField(db_index=True, null=True, blank=True)
    banner_group_spend = models.FloatField(default=0.0)
    views = models.IntegerField(default=0)
    clicks = models.IntegerField(default=0)
    ctr = models.FloatField(default=0.0)
    average_cpc = models.FloatField(default=0.0)
    direct_ppv = models.FloatField(default=0.0)
    direct_units = models.IntegerField(default=0)
    indirect_units = models.IntegerField(default=0)
    cvr = models.FloatField(default=0.0)
    direct_revenue = models.FloatField(default=0.0)
    indirect_revenue = models.FloatField(default=0.0)
    direct_roi = models.FloatField(default=0.0)
    indirect_roi = models.FloatField(default=0.0)

    class Meta:
        unique_together = ('user', 'campaign_id', 'ad_group_id', 'date')

class PLAFSNReport(models.Model):
    user = models.ForeignKey('accounts.Users', on_delete=models.CASCADE, related_name='pla_fsn_reports')
    start_time = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    campaign_id = models.CharField(max_length=100, null=True, blank=True)
    campaign_name = models.CharField(max_length=255, null=True, blank=True)
    ad_group_id = models.CharField(max_length=100, null=True, blank=True)
    ad_group_name = models.CharField(max_length=255, null=True, blank=True)
    advertised_fsn_id = models.CharField(max_length=100, db_index=True, null=True, blank=True)
    advertised_product_name = models.CharField(max_length=255, null=True, blank=True)
    views = models.IntegerField(default=0)
    clicks = models.IntegerField(default=0)
    ctr = models.FloatField(default=0.0)
    cvr = models.FloatField(default=0.0)
    ad_spend = models.FloatField(default=0.0)
    units_sold_direct = models.IntegerField(default=0)
    units_sold_indirect = models.IntegerField(default=0)
    direct_revenue = models.FloatField(default=0.0)
    indirect_revenue = models.FloatField(default=0.0)
    roi_direct = models.FloatField(default=0.0)
    roi_indirect = models.FloatField(default=0.0)

    class Meta:
        unique_together = ('user', 'campaign_id', 'ad_group_id', 'advertised_fsn_id')
