# Generated by Django 6.0.3 on 2026-04-10 08:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_feature_users_created_by_users_is_main_user_role_and_more'),
        ('dashboard', '0003_processeddashboarddata_idx_user_cat_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardFilterCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_key', models.CharField(help_text='Standard date range key, e.g. "last_7_days", "last_3_months".', max_length=50)),
                ('payload_json', models.JSONField(default=dict)),
                ('refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_filter_caches', to='accounts.users')),
            ],
            options={
                'verbose_name': 'Dashboard Filter Cache',
                'verbose_name_plural': 'Dashboard Filter Caches',
                'db_table': 'dashboard_filter_cache',
                'unique_together': {('user', 'filter_key')},
            },
        ),
    ]
