# Generated by Django 6.0.3 on 2026-04-13 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_feature_users_created_by_users_is_main_user_role_and_more"),
        ("dashboard", "0004_dashboardfiltercache"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlipkartCurrentInventoryReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warehouse_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sku", models.CharField(db_index=True, max_length=100)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("listing_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fsn",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("flipkart_selling_price", models.FloatField(default=0.0)),
                (
                    "live_on_website",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("sales_7d", models.IntegerField(default=0)),
                ("sales_14d", models.IntegerField(default=0)),
                ("sales_30d", models.IntegerField(default=0)),
                ("sales_60d", models.IntegerField(default=0)),
                ("sales_90d", models.IntegerField(default=0)),
                ("b2b_scheduled", models.IntegerField(default=0)),
                ("transfers_scheduled", models.IntegerField(default=0)),
                ("b2b_shipped", models.IntegerField(default=0)),
                ("transfers_shipped", models.IntegerField(default=0)),
                ("b2b_receiving", models.IntegerField(default=0)),
                ("transfers_receiving", models.IntegerField(default=0)),
                ("reserved_for_orders_and_recalls", models.IntegerField(default=0)),
                ("reserved_for_internal_processing", models.IntegerField(default=0)),
                ("returns_processing", models.IntegerField(default=0)),
                ("orders_to_dispatch", models.IntegerField(default=0)),
                ("recalls_to_dispatch", models.IntegerField(default=0)),
                ("damaged", models.IntegerField(default=0)),
                ("qc_reject", models.IntegerField(default=0)),
                ("catalog_reject", models.IntegerField(default=0)),
                ("returns_reject", models.IntegerField(default=0)),
                ("seller_return_reject", models.IntegerField(default=0)),
                ("miscellaneous", models.IntegerField(default=0)),
                ("length_in_cm", models.FloatField(default=0.0)),
                ("breadth_in_cm", models.FloatField(default=0.0)),
                ("height_in_cm", models.FloatField(default=0.0)),
                ("weight_in_kg", models.FloatField(default=0.0)),
                (
                    "fulfilment_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "f_assured_badge",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flipkart_inventory_reports",
                        to="accounts.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlipkartSalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seller_gstin",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("order_id", models.CharField(db_index=True, max_length=100)),
                ("order_item_id", models.CharField(db_index=True, max_length=100)),
                (
                    "product_title_description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "fsn",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("hsn_code", models.CharField(blank=True, max_length=100, null=True)),
                ("event_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "event_sub_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("order_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fulfilment_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("order_date", models.DateTimeField(blank=True, null=True)),
                ("order_approval_date", models.DateTimeField(blank=True, null=True)),
                ("item_quantity", models.IntegerField(default=0)),
                (
                    "order_shipped_from_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "warehouse_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("price_before_discount", models.FloatField(default=0.0)),
                ("total_discount", models.FloatField(default=0.0)),
                ("seller_share", models.FloatField(default=0.0)),
                ("bank_offer_share", models.FloatField(default=0.0)),
                ("price_after_discount", models.FloatField(default=0.0)),
                ("shipping_charges", models.FloatField(default=0.0)),
                ("final_invoice_amount", models.FloatField(default=0.0)),
                (
                    "type_of_tax",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("taxable_value", models.FloatField(default=0.0)),
                ("cst_rate", models.FloatField(default=0.0)),
                ("cst_amount", models.FloatField(default=0.0)),
                ("vat_rate", models.FloatField(default=0.0)),
                ("vat_amount", models.FloatField(default=0.0)),
                ("luxury_cess_rate", models.FloatField(default=0.0)),
                ("luxury_cess_amount", models.FloatField(default=0.0)),
                ("igst_rate", models.FloatField(default=0.0)),
                ("igst_amount", models.FloatField(default=0.0)),
                ("cgst_rate", models.FloatField(default=0.0)),
                ("cgst_amount", models.FloatField(default=0.0)),
                ("sgst_rate", models.FloatField(default=0.0)),
                ("sgst_amount", models.FloatField(default=0.0)),
                ("tcs_igst_rate", models.FloatField(default=0.0)),
                ("tcs_igst_amount", models.FloatField(default=0.0)),
                ("tcs_cgst_rate", models.FloatField(default=0.0)),
                ("tcs_cgst_amount", models.FloatField(default=0.0)),
                ("tcs_sgst_rate", models.FloatField(default=0.0)),
                ("tcs_sgst_amount", models.FloatField(default=0.0)),
                ("total_tcs_deducted", models.FloatField(default=0.0)),
                (
                    "buyer_invoice_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("buyer_invoice_date", models.DateTimeField(blank=True, null=True)),
                ("buyer_invoice_amount", models.FloatField(default=0.0)),
                (
                    "customer_billing_pincode",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "customer_billing_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer_delivery_pincode",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "customer_delivery_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("usual_price", models.FloatField(default=0.0)),
                (
                    "is_shopsy_order",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tds_rate", models.FloatField(default=0.0)),
                ("tds_amount", models.FloatField(default=0.0)),
                ("irn", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_gst_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "beneficiary_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("imei", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flipkart_sales_reports",
                        to="accounts.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PCADailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "campaign_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ad_group_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ad_group_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date", models.DateField(blank=True, db_index=True, null=True)),
                ("banner_group_spend", models.FloatField(default=0.0)),
                ("views", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("ctr", models.FloatField(default=0.0)),
                ("average_cpc", models.FloatField(default=0.0)),
                ("direct_ppv", models.FloatField(default=0.0)),
                ("direct_units", models.IntegerField(default=0)),
                ("indirect_units", models.IntegerField(default=0)),
                ("cvr", models.FloatField(default=0.0)),
                ("direct_revenue", models.FloatField(default=0.0)),
                ("indirect_revenue", models.FloatField(default=0.0)),
                ("direct_roi", models.FloatField(default=0.0)),
                ("indirect_roi", models.FloatField(default=0.0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pca_daily_reports",
                        to="accounts.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PLAFSNReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "campaign_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ad_group_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ad_group_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "advertised_fsn_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "advertised_product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("views", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("ctr", models.FloatField(default=0.0)),
                ("cvr", models.FloatField(default=0.0)),
                ("ad_spend", models.FloatField(default=0.0)),
                ("units_sold_direct", models.IntegerField(default=0)),
                ("units_sold_indirect", models.IntegerField(default=0)),
                ("direct_revenue", models.FloatField(default=0.0)),
                ("indirect_revenue", models.FloatField(default=0.0)),
                ("roi_direct", models.FloatField(default=0.0)),
                ("roi_indirect", models.FloatField(default=0.0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pla_fsn_reports",
                        to="accounts.users",
                    ),
                ),
            ],
        ),
    ]
