# Generated by Django 6.0.3 on 2026-04-13 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_feature_users_created_by_users_is_main_user_role_and_more'),
        ('dashboard', '0005_flipkartcurrentinventoryreport_flipkartsalesreport_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flipkartcurrentinventoryreport',
            unique_together={('user', 'warehouse_id', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='flipkartsalesreport',
            unique_together={('user', 'order_id', 'order_item_id')},
        ),
        migrations.AlterUniqueTogether(
            name='pcadailyreport',
            unique_together={('user', 'campaign_id', 'ad_group_id', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='plafsnreport',
            unique_together={('user', 'campaign_id', 'ad_group_id', 'advertised_fsn_id')},
        ),
    ]
