# Generated by Django 6.0.3 on 2026-04-16 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_flipkartprocesseddashboarddata_idx_fk_user_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorydashboardcache",
            name="user",
        ),
        migrations.RemoveField(
            model_name="ceodashboardcache",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="dashboardfiltercache",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="dashboardfiltercache",
            name="user",
        ),
        migrations.DeleteModel(
            name="BusinessDashboardCache",
        ),
        migrations.DeleteModel(
            name="CategoryDashboardCache",
        ),
        migrations.DeleteModel(
            name="CeoDashboardCache",
        ),
        migrations.DeleteModel(
            name="DashboardFilterCache",
        ),
    ]
