# Generated by Django 6.0.3 on 2026-04-16 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('dashboard', '0010_remove_categorydashboardcache_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlipkartCurrentInventoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('fsn', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('flipkart_selling_price', models.FloatField(default=0.0)),
                ('sales_30d', models.IntegerField(default=0)),
                ('returns_processing', models.IntegerField(default=0)),
                ('damaged', models.IntegerField(default=0)),
                ('in_stock_qty', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_inventory_reports', to='accounts.users')),
            ],
            options={
                'verbose_name': 'Flipkart Inventory Report',
            },
        ),
        migrations.CreateModel(
            name='FlipkartSalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=100)),
                ('order_item_id', models.CharField(db_index=True, max_length=100)),
                ('product_title_description', models.CharField(blank=True, max_length=500, null=True)),
                ('fsn', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('item_quantity', models.IntegerField(default=0)),
                ('taxable_value', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_sales_reports', to='accounts.users')),
            ],
            options={
                'unique_together': {('user', 'order_id', 'order_item_id')},
            },
        ),
    ]
