# Generated by Django 6.0.3 on 2026-04-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_flipkartcurrentinventoryreport_flipkartsalesreport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flipkartsalesreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='flipkartsalesreport',
            name='user',
        ),
        migrations.DeleteModel(
            name='FlipkartCurrentInventoryReport',
        ),
        migrations.DeleteModel(
            name='FlipkartSalesReport',
        ),
    ]
