# Generated by Django 6.0.3 on 2026-04-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('dashboard', '0012_alter_flipkartsalesreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flipkartprocesseddashboarddata',
            index=models.Index(fields=['user', 'date', 'portfolio', 'category'], name='idx_fk_u_d_p_c'),
        ),
        migrations.AddIndex(
            model_name='processeddashboarddata',
            index=models.Index(fields=['user', 'date', 'portfolio', 'category'], name='idx_u_d_p_c'),
        ),
    ]
