# Generated by Django 6.0.3 on 2026-05-07 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('dashboard', '0013_flipkartprocesseddashboarddata_idx_fk_u_d_p_c_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBAStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('fnsku', models.CharField(blank=True, max_length=50, null=True)),
                ('asin', models.CharField(db_index=True, max_length=50)),
                ('msku', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('disposition', models.CharField(blank=True, max_length=50, null=True)),
                ('starting_warehouse_balance', models.IntegerField(default=0)),
                ('in_transit_between_warehouses', models.IntegerField(default=0)),
                ('receipts', models.IntegerField(default=0)),
                ('customer_shipments', models.IntegerField(default=0)),
                ('customer_returns', models.IntegerField(default=0)),
                ('vendor_returns', models.IntegerField(default=0)),
                ('warehouse_transfer_in_out', models.IntegerField(default=0)),
                ('found', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('damaged', models.IntegerField(default=0)),
                ('disposed', models.IntegerField(default=0)),
                ('other_events', models.IntegerField(default=0)),
                ('ending_warehouse_balance', models.IntegerField(default=0)),
                ('unknown_events', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fba_stock_data', to='accounts.users')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'asin'], name='idx_fba_user_asin')],
                'unique_together': {('user', 'asin', 'date', 'disposition', 'location')},
            },
        ),
        migrations.CreateModel(
            name='FlexStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_index=True, max_length=50)),
                ('cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flex_stock_data', to='accounts.users')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'asin'], name='idx_flex_user_asin')],
                'unique_together': {('user', 'asin', 'cluster')},
            },
        ),
    ]
