# Generated by Django 6.0.3 on 2026-05-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('dashboard', '0014_fbastockdata_flexstockdata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flexstockdata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='flexstockdata',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='flexstockdata',
            unique_together={('user', 'asin', 'date', 'cluster')},
        ),
        migrations.AddIndex(
            model_name='flexstockdata',
            index=models.Index(fields=['user', 'asin', 'date'], name='idx_flex_u_a_d'),
        ),
    ]
