# Generated by Django 6.0.3 on 2026-05-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_flipkartpla_date_and_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flipkartpca',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='flipkartpca',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='flipkartsalesinvoice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='flipkartsalesinvoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='flipkartprocesseddashboarddata',
            name='coupon_error',
        ),
        migrations.RemoveField(
            model_name='flipkartprocesseddashboarddata',
            name='coupon_total',
        ),
        migrations.RemoveField(
            model_name='flipkartprocesseddashboarddata',
            name='invoice_amount',
        ),
        migrations.RemoveField(
            model_name='flipkartprocesseddashboarddata',
            name='taxable_value',
        ),
        migrations.DeleteModel(
            name='FlipkartCoupon',
        ),
        migrations.DeleteModel(
            name='FlipkartPCA',
        ),
        migrations.DeleteModel(
            name='FlipkartSalesInvoice',
        ),
    ]
