# Generated by Django 6.0.3 on 2026-05-13 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('dashboard', '0018_alter_flipkartpca_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlipkartInventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsn', models.CharField(db_index=True, max_length=50)),
                ('sku', models.CharField(blank=True, max_length=200, null=True)),
                ('product_status', models.CharField(blank=True, max_length=50, null=True)),
                ('product_type', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_inventory_stock', to='accounts.users')),
            ],
            options={
                'verbose_name': 'Flipkart Inventory Stock',
                'unique_together': {('user', 'fsn')},
            },
        ),
    ]
