# Generated by Django 6.0.3 on 2026-05-13 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('dashboard', '0020_dashboard_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMaterializedSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_type', models.CharField(db_index=True, default='shared', max_length=20)),
                ('data_version', models.BigIntegerField(db_index=True, default=0)),
                ('filter_hash', models.CharField(db_index=True, max_length=64)),
                ('normalized_filters', models.TextField()),
                ('payload_blob', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_materialized_summaries', to='accounts.users')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'view_type', 'data_version'], name='idx_dms_u_v_dv'), models.Index(fields=['user', 'updated_at'], name='idx_dms_u_upd')],
                'unique_together': {('user', 'view_type', 'data_version', 'filter_hash')},
            },
        ),
    ]
