# Generated by Django 6.0.3 on 2026-05-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('dashboard', '0021_dashboardmaterializedsummary'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flipkartprocesseddashboarddata',
            index=models.Index(fields=['user', 'fsn'], name='idx_fkpdd_u_fsn'),
        ),
        migrations.AddIndex(
            model_name='flipkartprocesseddashboarddata',
            index=models.Index(fields=['user', 'category'], name='idx_fkpdd_u_cat'),
        ),
        migrations.AddIndex(
            model_name='flipkartprocesseddashboarddata',
            index=models.Index(fields=['user', 'portfolio'], name='idx_fkpdd_u_port'),
        ),
        migrations.AddIndex(
            model_name='flipkartprocesseddashboarddata',
            index=models.Index(fields=['user', 'subcategory'], name='idx_fkpdd_u_sub'),
        ),
        migrations.AddIndex(
            model_name='processeddashboarddata',
            index=models.Index(fields=['user', 'asin'], name='idx_pdd_u_asin'),
        ),
        migrations.AddIndex(
            model_name='processeddashboarddata',
            index=models.Index(fields=['user', 'category'], name='idx_pdd_u_cat'),
        ),
        migrations.AddIndex(
            model_name='processeddashboarddata',
            index=models.Index(fields=['user', 'portfolio'], name='idx_pdd_u_port'),
        ),
        migrations.AddIndex(
            model_name='processeddashboarddata',
            index=models.Index(fields=['user', 'subcategory'], name='idx_pdd_u_sub'),
        ),
    ]
