# Generated by Django 6.0.3 on 2026-05-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_users_is_main_user"),
        ("dashboard", "0023_dashboard_filter_search_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flipkartfba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("fsn", models.CharField(db_index=True, max_length=50)),
                ("warehouse_id", models.CharField(blank=True, max_length=200, null=True)),
                ("sku", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("listing_id", models.CharField(blank=True, max_length=120, null=True)),
                ("brand", models.CharField(blank=True, max_length=120, null=True)),
                ("flipkart_selling_price", models.FloatField(default=0.0)),
                ("live_on_website", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_fba_stock_data",
                        to="accounts.users",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flipkart FBA",
                "unique_together": {("user", "date", "fsn", "warehouse_id")},
            },
        ),
        migrations.AddIndex(
            model_name="flipkartfba",
            index=models.Index(
                fields=["user", "date", "fsn"], name="idx_fkfba_u_d_fsn"
            ),
        ),
        migrations.AddIndex(
            model_name="flipkartfba",
            index=models.Index(fields=["user", "fsn"], name="idx_fkfba_u_fsn"),
        ),
    ]
