# Generated by Django 6.0.3 on 2026-05-19 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_spenddata_ad_type_agg_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='categorymapping',
            name='idx_cm_u_cat',
        ),
        migrations.RemoveIndex(
            model_name='categorymapping',
            name='idx_cm_u_port',
        ),
        migrations.RemoveIndex(
            model_name='categorymapping',
            name='idx_cm_u_sub',
        ),
        migrations.RemoveIndex(
            model_name='flipkartsearchtraffic',
            name='idx_fkst_u_date',
        ),
        migrations.RemoveIndex(
            model_name='flipkartsearchtraffic',
            name='idx_fkst_u_fsn',
        ),
        migrations.RemoveIndex(
            model_name='salesdata',
            name='idx_sales_u_date',
        ),
        migrations.RemoveIndex(
            model_name='salesdata',
            name='idx_sales_u_asin',
        ),
        migrations.RemoveIndex(
            model_name='spenddata',
            name='idx_spend_u_date',
        ),
        migrations.RemoveIndex(
            model_name='spenddata',
            name='idx_spend_u_asin',
        ),
    ]
