# Generated by Django 5.2.14 on 2026-05-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('dashboard', '0029_remove_categorymapping_idx_cm_u_cat_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flipkartpla',
            index=models.Index(fields=['user', 'date'], name='idx_fkpla_u_date'),
        ),
    ]
