# Generated by Django 5.2.14 on 2026-05-20 11:55

from django.db import migrations, models


def add_index_if_not_exists(apps, schema_editor):
    """Add index only if it doesn't already exist."""
    db_table = 'dashboard_flipkartpla'
    index_name = 'idx_fkpla_u_date'
    
    with schema_editor.connection.cursor() as cursor:
        # Check if index already exists
        cursor.execute(f"""
            SELECT 1 FROM information_schema.STATISTICS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = %s 
            AND INDEX_NAME = %s
        """, [db_table, index_name])
        
        if not cursor.fetchone():
            # Index doesn't exist, create it
            cursor.execute(f"""
                ALTER TABLE {db_table} 
                ADD INDEX {index_name} (user_id, date)
            """)


def reverse_index(apps, schema_editor):
    """Remove the index if it exists."""
    db_table = 'dashboard_flipkartpla'
    index_name = 'idx_fkpla_u_date'
    
    with schema_editor.connection.cursor() as cursor:
        # Check if index exists before dropping
        cursor.execute(f"""
            SELECT 1 FROM information_schema.STATISTICS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = %s 
            AND INDEX_NAME = %s
        """, [db_table, index_name])
        
        if cursor.fetchone():
            # Index exists, drop it
            cursor.execute(f"ALTER TABLE {db_table} DROP INDEX {index_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('dashboard', '0029_remove_categorymapping_idx_cm_u_cat_and_more'),
    ]

    operations = [
        migrations.RunPython(add_index_if_not_exists, reverse_index),
    ]
