# Generated by Django 6.0.3 on 2026-05-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('dashboard', '0032_dashboardasinmonthlysummary'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dashboardasinmonthlysummary',
            index=models.Index(fields=['user', 'subcategory', 'year_month'], name='idx_ams_u_sub_ym'),
        ),
        migrations.AddIndex(
            model_name='dashboardasinmonthlysummary',
            index=models.Index(fields=['user', 'platform', 'category', 'year_month'], name='idx_ams_u_p_cat_ym'),
        ),
        migrations.AddIndex(
            model_name='dashboardasinmonthlysummary',
            index=models.Index(fields=['user', 'platform', 'portfolio', 'year_month'], name='idx_ams_u_p_port_ym'),
        ),
        migrations.AddIndex(
            model_name='dashboardasinmonthlysummary',
            index=models.Index(fields=['user', 'platform', 'subcategory', 'year_month'], name='idx_ams_u_p_sub_ym'),
        ),
        migrations.AddIndex(
            model_name='dashboarddailysummary',
            index=models.Index(fields=['user', 'platform', 'category', 'date'], name='idx_dds_u_p_cat_d'),
        ),
        migrations.AddIndex(
            model_name='dashboarddailysummary',
            index=models.Index(fields=['user', 'platform', 'portfolio', 'date'], name='idx_dds_u_p_port_d'),
        ),
        migrations.AddIndex(
            model_name='dashboarddailysummary',
            index=models.Index(fields=['user', 'platform', 'subcategory', 'date'], name='idx_dds_u_p_sub_d'),
        ),
        migrations.AddIndex(
            model_name='dashboardinventoryhealthsummary',
            index=models.Index(fields=['user', 'platform', 'category', 'date'], name='idx_dihs_u_p_cat_d'),
        ),
        migrations.AddIndex(
            model_name='dashboardinventoryhealthsummary',
            index=models.Index(fields=['user', 'platform', 'portfolio', 'date'], name='idx_dihs_u_p_port_d'),
        ),
        migrations.AddIndex(
            model_name='dashboardinventoryhealthsummary',
            index=models.Index(fields=['user', 'platform', 'subcategory', 'date'], name='idx_dihs_u_p_sub_d'),
        ),
        migrations.AddIndex(
            model_name='flipkartprocesseddashboarddata',
            index=models.Index(fields=['user', 'category', 'portfolio', 'subcategory', 'date'], name='idx_fkpd_u_c_p_s_d'),
        ),
        migrations.AddIndex(
            model_name='flipkartprocesseddashboarddata',
            index=models.Index(fields=['user', 'date', 'category', 'portfolio', 'subcategory'], name='idx_fkpd_u_d_c_p_s'),
        ),
        migrations.AddIndex(
            model_name='flipkartsearchtraffic',
            index=models.Index(fields=['user', 'date', 'fsn'], name='idx_fkst_u_d_fsn'),
        ),
        migrations.AddIndex(
            model_name='processeddashboarddata',
            index=models.Index(fields=['user', 'category', 'portfolio', 'subcategory', 'date'], name='idx_pdd_u_c_p_s_d'),
        ),
        migrations.AddIndex(
            model_name='processeddashboarddata',
            index=models.Index(fields=['user', 'date', 'category', 'portfolio', 'subcategory'], name='idx_pdd_u_d_c_p_s'),
        ),
    ]
