# Generated by Django 6.0.3 on 2026-05-29 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('dashboard', '0033_dashboardasinmonthlysummary_idx_ams_u_sub_ym_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsinFsnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_index=True, max_length=50)),
                ('fsn', models.CharField(db_index=True, max_length=80)),
                ('category', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('portfolio', models.CharField(blank=True, max_length=120, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'ASIN-FSN Mapping',
                'verbose_name_plural': 'ASIN-FSN Mappings',
            },
        ),
        migrations.AddField(
            model_name='dashboardinventoryhealthsummary',
            name='asin',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dashboardinventoryhealthsummary',
            name='fk_doc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dashboardinventoryhealthsummary',
            name='fk_fba_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardinventoryhealthsummary',
            name='fk_flex_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardinventoryhealthsummary',
            name='fk_revenue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dashboardinventoryhealthsummary',
            name='fk_sale_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardinventoryhealthsummary',
            name='fk_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dashboardinventoryhealthsummary',
            name='fk_status_class',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='dashboardinventoryhealthsummary',
            name='fk_stock_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardinventoryhealthsummary',
            name='fsn',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AddIndex(
            model_name='dashboardinventoryhealthsummary',
            index=models.Index(fields=['user', 'asin', 'date'], name='idx_dihs_u_asin_d'),
        ),
        migrations.AddIndex(
            model_name='dashboardinventoryhealthsummary',
            index=models.Index(fields=['user', 'fsn', 'date'], name='idx_dihs_u_fsn_d'),
        ),
        migrations.AddField(
            model_name='asinfsnmapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asin_fsn_mappings', to='accounts.users'),
        ),
        migrations.AddIndex(
            model_name='asinfsnmapping',
            index=models.Index(fields=['user', 'asin'], name='idx_afm_u_asin'),
        ),
        migrations.AddIndex(
            model_name='asinfsnmapping',
            index=models.Index(fields=['user', 'fsn'], name='idx_afm_u_fsn'),
        ),
        migrations.AddIndex(
            model_name='asinfsnmapping',
            index=models.Index(fields=['user', 'category'], name='idx_afm_u_cat'),
        ),
        migrations.AlterUniqueTogether(
            name='asinfsnmapping',
            unique_together={('user', 'asin', 'fsn')},
        ),
    ]
