# Generated by Django 6.0.3 on 2026-06-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_asinfsnmapping_dashboardinventoryhealthsummary_asin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymapping',
            name='msku',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
