# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0035_add_msku_to_category_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymapping",
            name="parent_asin",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
