# Generated by Django 6.0.3 on 2026-06-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_category_mapping_filter_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymapping',
            name='colour',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flipkartcategorymap',
            name='colour',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
