# Generated by Django 6.0.3 on 2026-06-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_categorymapping_colour_flipkartcategorymap_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymapping',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='flipkartcategorymap',
            name='colour',
        ),
    ]
