# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0039_remove_categorymapping_colour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymapping",
            name="launch_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="flipkartcategorymap",
            name="launch_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
