# Generated by Django 6.0.3 on 2026-06-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('dashboard', '0043_dashboard_query_optimization_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dashboardproductdailysummary',
            index=models.Index(fields=['user', 'platform', 'date', 'asin'], name='idx_dpds_u_p_d_asn'),
        ),
        migrations.AddIndex(
            model_name='dashboardproductdailysummary',
            index=models.Index(fields=['user', 'platform', 'date', 'fsn'], name='idx_dpds_u_p_d_fsn'),
        ),
    ]
