# Generated by Django 6.0.3 on 2026-06-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('dashboard', '0044_dashboardproductdailysummary_idx_dpds_u_p_d_asn_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dashboardproductdailysummary',
            index=models.Index(fields=['user', 'platform', 'date', 'sku'], name='idx_dpds_u_p_d_sku'),
        ),
        migrations.AddIndex(
            model_name='dashboardproductdailysummary',
            index=models.Index(fields=['user', 'date', 'sku'], name='idx_dpds_u_d_sku'),
        ),
    ]
