# Generated by Django 6.0.3 on 2026-06-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('dashboard', '0045_dashboardproductdailysummary_idx_dpds_u_p_d_sku_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dashboardproductdailysummary',
            name='idx_dpds_u_p_d_asn',
        ),
        migrations.RemoveIndex(
            model_name='dashboardproductdailysummary',
            name='idx_dpds_u_p_d_fsn',
        ),
        migrations.RemoveIndex(
            model_name='dashboardproductdailysummary',
            name='idx_dpds_u_d_sku',
        ),
        migrations.RenameIndex(
            model_name='dashboardproductdailysummary',
            new_name='idx_dpds_u_p_d_s',
            old_name='idx_dpds_u_p_d_sku',
        ),
        migrations.AddIndex(
            model_name='dashboardproductdailysummary',
            index=models.Index(fields=['user', 'platform', 'date'], name='idx_dpds_u_p_d'),
        ),
    ]
