# Generated by Django 6.0.3 on 2026-06-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('dashboard', '0046_remove_dashboardproductdailysummary_idx_dpds_u_p_d_asn_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dashboardproductdailysummary',
            index=models.Index(fields=['user', 'platform', 'fsn'], name='idx_dpds_u_p_fsn'),
        ),
    ]
