# Generated by Django 6.0.3 on 2026-06-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_dashboardproductdailysummary_idx_dpds_u_p_fsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardproductdailysummary',
            name='spend_sb',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dashboardproductdailysummary',
            name='spend_sd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dashboardproductdailysummary',
            name='spend_sp',
            field=models.FloatField(default=0.0),
        ),
    ]
