# Generated by Django 6.0.3 on 2026-07-03 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('dashboard', '0051_materialized_summary_section_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMappingDimensionDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('platform', models.CharField(db_index=True, max_length=20)),
                ('dimension_hash', models.CharField(db_index=True, max_length=40)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('portfolio', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('category_manager', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('series_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('brand_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('ratings', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('finish', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('revenue', models.FloatField(default=0.0)),
                ('orders', models.IntegerField(default=0)),
                ('units', models.IntegerField(default=0)),
                ('pageviews', models.IntegerField(default=0)),
                ('total_spend', models.FloatField(default=0.0)),
                ('spend_sp', models.FloatField(default=0.0)),
                ('spend_sb', models.FloatField(default=0.0)),
                ('spend_sd', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_mapping_dimension_daily_summaries', to='accounts.users')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date', 'platform'], name='idx_dmds_u_d_p'), models.Index(fields=['user', 'platform', 'date'], name='idx_dmds_u_p_d'), models.Index(fields=['user', 'category_manager', 'date'], name='idx_dmds_u_mgr_d'), models.Index(fields=['user', 'series_name', 'date'], name='idx_dmds_u_series_d'), models.Index(fields=['user', 'material', 'date'], name='idx_dmds_u_mat_d'), models.Index(fields=['user', 'size', 'date'], name='idx_dmds_u_size_d'), models.Index(fields=['user', 'finish', 'date'], name='idx_dmds_u_finish_d'), models.Index(fields=['user', 'brand_name', 'date'], name='idx_dmds_u_brand_d'), models.Index(fields=['user', 'ratings', 'date'], name='idx_dmds_u_rating_d'), models.Index(fields=['user', 'platform', 'category_manager', 'date'], name='idx_dmds_u_p_mgr_d'), models.Index(fields=['user', 'platform', 'material', 'date'], name='idx_dmds_u_p_mat_d')],
                'unique_together': {('user', 'date', 'platform', 'dimension_hash')},
            },
        ),
    ]
