# Generated by Django 6.0.3 on 2026-07-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_dashboardmappingdimensiondailysummary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dashboardmappingdimensiondailysummary',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dashboardmappingdimensiondailysummary',
            name='dimension_hash',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
