# Generated by Django 6.0.3 on 2026-07-03 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('dashboard', '0053_alter_dashboardmappingdimensiondailysummary_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMappingFilterDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('platform', models.CharField(db_index=True, max_length=20)),
                ('filter_name', models.CharField(db_index=True, max_length=40)),
                ('filter_value', models.CharField(db_index=True, max_length=120)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('portfolio', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('revenue', models.FloatField(default=0.0)),
                ('orders', models.IntegerField(default=0)),
                ('units', models.IntegerField(default=0)),
                ('pageviews', models.IntegerField(default=0)),
                ('total_spend', models.FloatField(default=0.0)),
                ('spend_sp', models.FloatField(default=0.0)),
                ('spend_sb', models.FloatField(default=0.0)),
                ('spend_sd', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_mapping_filter_daily_summaries', to='accounts.users')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'filter_name', 'filter_value', 'date'], name='idx_dmfs_u_n_v_d'), models.Index(fields=['user', 'platform', 'filter_name', 'filter_value', 'date'], name='idx_dmfs_u_p_n_v_d'), models.Index(fields=['user', 'filter_name', 'date'], name='idx_dmfs_u_n_d'), models.Index(fields=['user', 'platform', 'date'], name='idx_dmfs_u_p_d')],
            },
        ),
    ]
