# Generated by Django 6.0.3 on 2026-07-03 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_is_main_user'),
        ('dashboard', '0054_dashboardmappingfilterdailysummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMappingFilterMonthlyActivitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(db_index=True)),
                ('platform', models.CharField(db_index=True, max_length=20)),
                ('filter_name', models.CharField(db_index=True, max_length=40)),
                ('filter_value', models.CharField(db_index=True, max_length=120)),
                ('sku', models.CharField(db_index=True, max_length=80)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('portfolio', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('subcategory', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('units', models.IntegerField(default=0)),
                ('pageviews', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_mapping_filter_monthly_activity_summaries', to='accounts.users')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'filter_name', 'filter_value', 'year_month'], name='idx_dmfma_u_n_v_m'), models.Index(fields=['user', 'platform', 'filter_name', 'filter_value', 'year_month'], name='idx_dmfma_u_p_n_v_m'), models.Index(fields=['user', 'filter_name', 'filter_value', 'sku', 'year_month'], name='idx_dmfma_u_n_v_s_m'), models.Index(fields=['user', 'platform', 'filter_name', 'filter_value', 'sku', 'year_month'], name='idx_dmfma_u_p_nvs_m')],
            },
        ),
    ]
