# Generated by Django 6.0.3 on 2026-07-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_dashboardmappingfiltermonthlyactivitysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmappingfiltermonthlyactivitysummary',
            name='revenue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dashboardmappingfiltermonthlyactivitysummary',
            name='total_spend',
            field=models.FloatField(default=0.0),
        ),
    ]
